import 'package:cloud_firestore/cloud_firestore.dart';
import 'firebase_service.dart';

class SeedService {
  static final FirebaseFirestore _firestore = FirebaseService.firestore;

  /// Seeds the products collection with sample data
  /// Call this ONCE from a debug button or initial setup
  static Future<void> seedProducts() async {
    final productsCollection = _firestore.collection('products');

    final now = DateTime.now().toIso8601String();
    final fakeReviews = [
      {
        'userId': 'user_001',
        'userName': 'Aser Abdo',
        'comment': 'Amazing product! Highly recommend.',
        'rating': 5.0,
        'createdAt': now,
      },
      {
        'userId': 'user_002',
        'userName': 'Sara Ahmed',
        'comment': 'Good value for money.',
        'rating': 4.0,
        'createdAt': now,
      },
      {
        'userId': 'user_003',
        'userName': 'Mohamed Ali',
        'comment': 'Decent, but could be better.',
        'rating': 3.5,
        'createdAt': now,
      },
    ];

    final products = [
      // Electronics (8 products)
      {
        'id': 'prod_001',
        'name': 'iPhone 15 Pro Max',
        'description':
            'Latest Apple smartphone with A17 Pro chip, titanium design, and advanced camera system',
        'price': 52000.0,
        'category': 'Electronics',
        'imageUrl': 'https://picsum.photos/seed/iphone15/400/400',
        'stock': 25,
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
        'reviews': fakeReviews,
      },
      {
        'id': 'prod_002',
        'name': 'Samsung Galaxy S24 Ultra',
        'description':
            'Premium Android flagship with AI features, S Pen, and 200MP camera',
        'price': 48000.0,
        'category': 'Electronics',
        'imageUrl': 'https://picsum.photos/seed/galaxys24/400/400',
        'stock': 30,
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
        'reviews': fakeReviews,
      },
      {
        'id': 'prod_003',
        'name': 'Sony WH-1000XM5',
        'description':
            'Wireless noise-canceling headphones with premium sound quality',
        'price': 15000.0,
        'category': 'Electronics',
        'imageUrl': 'https://picsum.photos/seed/sonyheadphones/400/400',
        'stock': 50,
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
        'reviews': fakeReviews,
      },
      {
        'id': 'prod_004',
        'name': 'Apple Watch Series 9',
        'description': 'Advanced fitness and health tracking smartwatch',
        'price': 18000.0,
        'category': 'Electronics',
        'imageUrl': 'https://picsum.photos/seed/applewatch9/400/400',
        'stock': 40,
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
        'reviews': fakeReviews,
      },
      {
        'id': 'prod_005',
        'name': 'iPad Air M2',
        'description':
            'Powerful tablet with M2 chip, 11-inch Liquid Retina display',
        'price': 28000.0,
        'category': 'Electronics',
        'imageUrl': 'https://picsum.photos/seed/ipadair/400/400',
        'stock': 20,
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
        'reviews': fakeReviews,
      },
      {
        'id': 'prod_016',
        'name': 'MacBook Pro M3',
        'description': '14-inch laptop with M3 chip, 16GB RAM, 512GB SSD',
        'price': 85000.0,
        'category': 'Electronics',
        'imageUrl': 'https://picsum.photos/seed/macbookpro/400/400',
        'stock': 15,
        'reviews': fakeReviews,
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prod_017',
        'name': 'AirPods Pro 2',
        'description':
            'Active noise cancellation, spatial audio, USB-C charging',
        'price': 9500.0,
        'category': 'Electronics',
        'imageUrl': 'https://picsum.photos/seed/airpodspro/400/400',
        'stock': 60,
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prod_018',
        'name': 'PlayStation 5',
        'description':
            'Next-gen gaming console with 4K gaming and ultra-fast SSD',
        'price': 22000.0,
        'category': 'Electronics',
        'imageUrl': 'https://picsum.photos/seed/ps5/400/400',
        'stock': 12,
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },

      // Fashion (8 products)
      {
        'id': 'prod_006',
        'name': 'Nike Air Max 270',
        'description':
            'Comfortable running shoes with air cushioning technology',
        'price': 3500.0,
        'category': 'Fashion',
        'imageUrl': 'https://picsum.photos/seed/nikeairmax/400/400',
        'stock': 100,
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prod_007',
        'name': 'Adidas Ultraboost',
        'description': 'Premium running shoes with responsive boost cushioning',
        'price': 4200.0,
        'category': 'Fashion',
        'imageUrl': 'https://picsum.photos/seed/ultraboost/400/400',
        'stock': 80,
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prod_008',
        'name': 'Levi\'s 501 Jeans',
        'description': 'Classic straight-fit denim jeans, authentic style',
        'price': 2800.0,
        'category': 'Fashion',
        'imageUrl': 'https://picsum.photos/seed/levis501/400/400',
        'stock': 120,
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prod_009',
        'name': 'Ray-Ban Aviator',
        'description': 'Iconic sunglasses with metal frame and UV protection',
        'price': 1500.0,
        'category': 'Fashion',
        'imageUrl': 'https://picsum.photos/seed/rayban/400/400',
        'stock': 60,
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prod_010',
        'name': 'Zara Leather Jacket',
        'description': 'Premium genuine leather jacket, modern design',
        'price': 5500.0,
        'category': 'Fashion',
        'imageUrl': 'https://picsum.photos/seed/zarajacket/400/400',
        'stock': 35,
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prod_019',
        'name': 'H&M Cotton T-Shirt',
        'description': 'Basic cotton t-shirt, available in multiple colors',
        'price': 450.0,
        'category': 'Fashion',
        'imageUrl': 'https://picsum.photos/seed/hmtshirt/400/400',
        'stock': 200,
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prod_020',
        'name': 'Gucci Belt',
        'description': 'Luxury leather belt with iconic GG buckle',
        'price': 12000.0,
        'category': 'Fashion',
        'imageUrl': 'https://picsum.photos/seed/guccibelt/400/400',
        'stock': 25,
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prod_021',
        'name': 'Converse Chuck Taylor',
        'description': 'Classic canvas sneakers, timeless design',
        'price': 1800.0,
        'category': 'Fashion',
        'imageUrl': 'https://picsum.photos/seed/converse/400/400',
        'stock': 90,
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },

      // Home (7 products)
      {
        'id': 'prod_011',
        'name': 'Dyson V15 Vacuum',
        'description':
            'Cordless vacuum cleaner with laser detection technology',
        'price': 22000.0,
        'category': 'Home',
        'imageUrl': 'https://picsum.photos/seed/dysonv15/400/400',
        'stock': 15,
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prod_012',
        'name': 'Nespresso Coffee Machine',
        'description': 'Premium espresso and coffee maker with milk frother',
        'price': 8500.0,
        'category': 'Home',
        'imageUrl': 'https://picsum.photos/seed/nespresso/400/400',
        'stock': 25,
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prod_013',
        'name': 'IKEA Minimalist Desk',
        'description':
            'Modern white desk with cable management, perfect for home office',
        'price': 3200.0,
        'category': 'Home',
        'imageUrl': 'https://picsum.photos/seed/ikeadesk/400/400',
        'stock': 40,
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prod_022',
        'name': 'Philips Air Fryer',
        'description':
            'Healthy cooking with rapid air technology, 4.1L capacity',
        'price': 3800.0,
        'category': 'Home',
        'imageUrl': 'https://picsum.photos/seed/airfryer/400/400',
        'stock': 35,
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prod_023',
        'name': 'Samsung Smart TV 55"',
        'description': '4K QLED TV with smart features and HDR',
        'price': 32000.0,
        'category': 'Home',
        'imageUrl': 'https://picsum.photos/seed/samsungtv/400/400',
        'stock': 18,
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prod_024',
        'name': 'Instant Pot Duo',
        'description': '7-in-1 electric pressure cooker, 6 quart',
        'price': 4500.0,
        'category': 'Home',
        'imageUrl': 'https://picsum.photos/seed/instantpot/400/400',
        'stock': 30,
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prod_025',
        'name': 'Roomba Robot Vacuum',
        'description': 'Smart robot vacuum with mapping and app control',
        'price': 15000.0,
        'category': 'Home',
        'imageUrl': 'https://picsum.photos/seed/roomba/400/400',
        'stock': 20,
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },

      // Beauty (7 products)
      {
        'id': 'prod_014',
        'name': 'Dior Sauvage Perfume',
        'description': 'Men\'s luxury fragrance, 100ml eau de toilette',
        'price': 4800.0,
        'category': 'Beauty',
        'imageUrl': 'https://picsum.photos/seed/diorsauvage/400/400',
        'stock': 70,
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prod_015',
        'name': 'Fenty Beauty Foundation',
        'description':
            'Pro Filt\'r Soft Matte foundation, full coverage, 40 shades',
        'price': 1800.0,
        'category': 'Beauty',
        'imageUrl': 'https://picsum.photos/seed/fentybeauty/400/400',
        'stock': 90,
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prod_026',
        'name': 'MAC Ruby Woo Lipstick',
        'description': 'Iconic matte red lipstick, retro matte formula',
        'price': 950.0,
        'category': 'Beauty',
        'imageUrl': 'https://picsum.photos/seed/maclipstick/400/400',
        'stock': 100,
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prod_027',
        'name': 'The Ordinary Serum Set',
        'description':
            'Skincare essentials set with hyaluronic acid and niacinamide',
        'price': 1200.0,
        'category': 'Beauty',
        'imageUrl': 'https://picsum.photos/seed/theordinary/400/400',
        'stock': 80,
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prod_028',
        'name': 'Chanel No. 5',
        'description': 'Iconic women\'s perfume, 100ml eau de parfum',
        'price': 6500.0,
        'category': 'Beauty',
        'imageUrl': 'https://picsum.photos/seed/chanelno5/400/400',
        'stock': 45,
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prod_029',
        'name': 'Urban Decay Eyeshadow Palette',
        'description': 'Naked palette with 12 neutral shades',
        'price': 2200.0,
        'category': 'Beauty',
        'imageUrl': 'https://picsum.photos/seed/urbandecay/400/400',
        'stock': 55,
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prod_030',
        'name': 'Dyson Airwrap',
        'description': 'Multi-styler for hair drying and styling',
        'price': 18000.0,
        'category': 'Beauty',
        'imageUrl': 'https://picsum.photos/seed/dysonairwrap/400/400',
        'stock': 22,
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },

      // Supermarket (10 products)
      {
        'id': 'prod_031',
        'name': 'Organic Whole Milk',
        'description': 'Fresh organic whole milk, 1 Gallon',
        'price': 120.0,
        'category': 'Supermarket',
        'imageUrl': 'https://picsum.photos/seed/milk/400/400',
        'stock': 50,
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prod_032',
        'name': 'Whole Wheat Bread',
        'description': 'Freshly baked whole wheat bread loaf',
        'price': 45.0,
        'category': 'Supermarket',
        'imageUrl': 'https://picsum.photos/seed/bread/400/400',
        'stock': 40,
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prod_033',
        'name': 'Free Range Eggs',
        'description': 'Carton of 12 large free-range eggs',
        'price': 160.0,
        'category': 'Supermarket',
        'imageUrl': 'https://picsum.photos/seed/eggs/400/400',
        'stock': 60,
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prod_034',
        'name': 'Basmati Rice',
        'description': 'Premium long-grain basmati rice, 5kg bag',
        'price': 450.0,
        'category': 'Supermarket',
        'imageUrl': 'https://picsum.photos/seed/rice/400/400',
        'stock': 100,
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prod_035',
        'name': 'Extra Virgin Olive Oil',
        'description': 'Cold-pressed extra virgin olive oil, 1L',
        'price': 380.0,
        'category': 'Supermarket',
        'imageUrl': 'https://picsum.photos/seed/oliveoil/400/400',
        'stock': 30,
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prod_036',
        'name': 'Chicken Breast Fillets',
        'description': 'Fresh boneless skinless chicken breast, 1kg',
        'price': 220.0,
        'category': 'Supermarket',
        'imageUrl': 'https://picsum.photos/seed/chicken/400/400',
        'stock': 25,
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prod_037',
        'name': 'Italian Pasta',
        'description': 'Authentic Italian spaghetti, 500g pack',
        'price': 35.0,
        'category': 'Supermarket',
        'imageUrl': 'https://picsum.photos/seed/pasta/400/400',
        'stock': 150,
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prod_038',
        'name': 'Cheddar Cheese',
        'description': 'Sharp cheddar cheese block, 200g',
        'price': 140.0,
        'category': 'Supermarket',
        'imageUrl': 'https://picsum.photos/seed/cheese/400/400',
        'stock': 45,
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prod_039',
        'name': 'Fresh Apples',
        'description': 'Crisp red apples, 1kg bag',
        'price': 80.0,
        'category': 'Supermarket',
        'imageUrl': 'https://picsum.photos/seed/apples/400/400',
        'stock': 70,
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prod_040',
        'name': 'Ground Coffee',
        'description': 'Medium roast arabica ground coffee, 250g',
        'price': 190.0,
        'category': 'Supermarket',
        'imageUrl': 'https://picsum.photos/seed/coffee/400/400',
        'stock': 55,
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },

      // Books (5 products)
      {
        'id': 'prod_041',
        'name': 'The Great Gatsby',
        'description': 'Classic novel by F. Scott Fitzgerald',
        'price': 250.0,
        'category': 'Books',
        'imageUrl': 'https://picsum.photos/seed/gatsby/400/400',
        'stock': 30,
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prod_042',
        'name': 'Atomic Habits',
        'description': 'Self-help book by James Clear',
        'price': 400.0,
        'category': 'Books',
        'imageUrl': 'https://picsum.photos/seed/atomichabits/400/400',
        'stock': 100,
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prod_043',
        'name': 'Harry Potter & The Sorcerer\'s Stone',
        'description': 'Fantasy novel by J.K. Rowling',
        'price': 350.0,
        'category': 'Books',
        'imageUrl': 'https://picsum.photos/seed/harrypotter/400/400',
        'stock': 50,
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prod_044',
        'name': 'Clean Code',
        'description': 'A Handbook of Agile Software Craftsmanship',
        'price': 850.0,
        'category': 'Books',
        'imageUrl': 'https://picsum.photos/seed/cleancode/400/400',
        'stock': 20,
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prod_045',
        'name': 'The Alchemist',
        'description': 'Novel by Paulo Coelho',
        'price': 280.0,
        'category': 'Books',
        'imageUrl': 'https://picsum.photos/seed/alchemist/400/400',
        'stock': 40,
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },

      // Sports (5 products)
      {
        'id': 'prod_046',
        'name': 'Yoga Mat',
        'description': 'Non-slip exercise yoga mat with carrying strap',
        'price': 450.0,
        'category': 'Sports',
        'imageUrl': 'https://picsum.photos/seed/yogamat/400/400',
        'stock': 60,
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prod_047',
        'name': 'Dumbbell Set',
        'description': 'Pair of 5kg neoprene coated dumbbells',
        'price': 900.0,
        'category': 'Sports',
        'imageUrl': 'https://picsum.photos/seed/dumbbells/400/400',
        'stock': 25,
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prod_048',
        'name': 'Football',
        'description': 'Professional size 5 soccer ball',
        'price': 650.0,
        'category': 'Sports',
        'imageUrl': 'https://picsum.photos/seed/football/400/400',
        'stock': 40,
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prod_049',
        'name': 'Tennis Racket',
        'description': 'Lightweight graphite tennis racket for beginners',
        'price': 1200.0,
        'category': 'Sports',
        'imageUrl': 'https://picsum.photos/seed/tennis/400/400',
        'stock': 15,
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prod_050',
        'name': 'Running Water Bottle',
        'description': 'Insulated stainless steel water bottle, 750ml',
        'price': 350.0,
        'category': 'Sports',
        'imageUrl': 'https://picsum.photos/seed/bottle/400/400',
        'stock': 80,
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },

      // Toys (5 products)
      {
        'id': 'prod_051',
        'name': 'Lego Classic Set',
        'description': 'Creative brick box with 484 pieces',
        'price': 1500.0,
        'category': 'Toys',
        'imageUrl': 'https://picsum.photos/seed/lego/400/400',
        'stock': 35,
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prod_052',
        'name': 'Barbie Dreamhouse',
        'description': '3-story dollhouse with pool and slide',
        'price': 4500.0,
        'category': 'Toys',
        'imageUrl': 'https://picsum.photos/seed/barbie/400/400',
        'stock': 10,
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prod_053',
        'name': 'Hot Wheels 10-Pack',
        'description': 'Set of 10 1:64 scale die-cast cars',
        'price': 600.0,
        'category': 'Toys',
        'imageUrl': 'https://picsum.photos/seed/hotwheels/400/400',
        'stock': 50,
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prod_054',
        'name': 'Teddy Bear',
        'description': 'Soft and cuddly plush teddy bear, 50cm',
        'price': 350.0,
        'category': 'Toys',
        'imageUrl': 'https://picsum.photos/seed/teddy/400/400',
        'stock': 40,
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prod_055',
        'name': 'Jigsaw Puzzle',
        'description': '1000-piece landscape puzzle',
        'price': 250.0,
        'category': 'Toys',
        'imageUrl': 'https://picsum.photos/seed/puzzle/400/400',
        'stock': 60,
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
    ];

    // Add products to Firestore
    try {
      for (final product in products) {
        final productId = product['id'] as String;
        await productsCollection.doc(productId).set(product);
        print('✅ Added product: ${product['name']}');
      }
      print('🎉 Successfully seeded ${products.length} products!');
    } catch (e) {
      print('❌ Error seeding products: $e');
      rethrow;
    }
  }

  /// Check if products collection is empty
  static Future<bool> isProductsEmpty() async {
    final snapshot = await _firestore.collection('products').limit(1).get();
    return snapshot.docs.isEmpty;
  }

  /// Delete all products (for testing/reset)
  static Future<void> clearProducts() async {
    final snapshot = await _firestore.collection('products').get();
    for (final doc in snapshot.docs) {
      await doc.reference.delete();
    }
    print('🗑️ Cleared all products');
  }
}
